server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: sb-websocket-one-chat

  data:
    mongodb:
      username: magadiflo
      password: magadiflo
      host: localhost
      port: 27017
      database: db_sb_websocket_one_chat
      authentication-database: admin
